### ISSUE TITLE
Formatting undefined date in an edge template shows 1/1/1970

### ISSUE THREAD

**Issue by anaq1** [adonisjs/i18n#121] opened 2022-10-10 12:38 UTC
## Package version
1.5.6

## Node.js and npm version
Node.js 18.4.0
npm 18.12.1

## Sample Code (to reproduce the issue)
Create an edge template with an undefined date (in this example myObject.date is undefined)
{{ i18n.formatDate(myObject.date) }}

Expected output: empty string (or at least an error), but it shows 1/1/1970

**Comment by thetutlage** [comment] 2022-10-11 10:43
Just tested with undefined value and the method returns the current date (the behavior is same as `Intl` API).

Please reproduce this issue in a fresh project and share its repo with me

**Comment by RomainLanz** [comment] 2022-11-13 21:20
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2022-11-13 21:20 UTC
